version: '3.7'

services:
  server:
    container_name: server
    build:
      context: server
    environment:
      MONGODB_URI: mongodb://mongodb:27017/database
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:7.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "p4ssw0rd"
    volumes:
      - "./mongodb-data:/data/db"
