version: '3.7'

services:
  tags:
    container_name: tags
    build:
      context: .
      dockerfile: ./services/tags/Dockerfile
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_DATABASE: "database"
      MONGODB_USER: "user"
      MONGODB_PASSWORD: "p4ssw0rd"
    depends_on:
      - mongodb
    ports:
      - "3001:3000"
      - "5001:5000"

  bot:
    container_name: bot
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./services/bot/Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
    depends_on:
      - tags
    ports:
      - "3002:3000"

  mongodb:
    container_name: mongodb
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "p4ssw0rd"
    volumes:
      - "./mongodb-data:/data/db"
