version: '3.7'

services:
  server:
    container_name: server
    build:
      context: server
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_DATABASE: "database"
      MONGODB_USER: "user"
      MONGODB_PASSWORD: "p4ssw0rd"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    container_name: mongodb
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "user"
      MONGO_INITDB_ROOT_PASSWORD: "p4ssw0rd"
    volumes:
      - "./mongodb-data:/data/db"
