apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tags
  template:
    metadata:
      labels:
        app: tags
    spec:
      containers:
        - name: tags
          image: tag-media-bot/tags:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017"
            - name: MONGODB_DATABASE
              value: "database"
            - name: MONGODB_USER
              value: "user"
            - name: MONGODB_PASSWORD
              value: "p4ssw0rd"
---

apiVersion: v1
kind: Service
metadata:
  name: tags-service
spec:
  type: NodePort
  selector:
    app: tags
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001
