apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: localhost:5000/tmb-server:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017"
            - name: MONGODB_DATABASE
              value: "database"
            - name: MONGODB_USER
              value: "user"
            - name: MONGODB_PASSWORD
              value: "p4ssw0rd"
---

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001
